<?php
// Load translation data
$this->i18nTheme('main');

// Load Bootstrap css by Twitter Team
$this->bootstrap(array(
    'css/font-awesome.min.css'
));

// Load style.css
$this->css(array(
    $this->assetTheme('css/style.css')
));
$this->jQuery();
$this->js($this->assetTheme('js/navigation.js'));

/**#@+
 * For demonstration
 */
/*
// Load jQuerty
$this->jQuery();
// Load locale css/js, optional
$this->css($this->assetLocale('rtl.css'));
$this->js($this->assetLocale('rtl.js'));
*/
/**#@-*/
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <?php echo $this->assemble('headTitle', 4); ?>
    <?php echo $this->assemble('headMeta', 4); ?>
    <?php echo $this->assemble('headLink', 4); ?>
    <?php echo $this->assemble('headStyle', 4); ?>
    <?php echo $this->assemble('headScript', 4); ?>
</head>

<body id="pi-<?php echo Pi::service('module')->current(); ?>" class="<?php echo $locale; ?>">
    <!-- header: sitename -->
    <div class="header">
        <div class="container">
            <a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>" class="sitename"><?php echo $this->escape($sitename); ?></a>
        </div>
    </div>
    <!-- navigation  -->
    <div class="container navbar">
        <div class="navbar-inner">
        <a href="/" class="brand">Pi</a>
        <?php 
            $navigation = $this->nav('front'/*, array('cache_ttl' => null, 'cache_level' => 'role')*/);
            echo $navigation->menu()->setUlClass('nav default-nav'); 
        ?>
        </div>
    </div>
    <!-- breadcrumbs: check if it exists  -->
    <?php $breadcrumbs = $navigation->breadcrumbs()->setSeparator('<span class="divider">&gt;</span>')->render(); ?>
    <?php if ($breadcrumbs) { ?>
    <div class="breadcrumb">
       <?php echo $breadcrumbs; ?> 
    </div>
    <?php } ?>

    <!-- page main content: blocks and module content -->
    <div class="container">
        <?php
            $blocks = $this->blocks();
            $blockTempalte = $this->template('block');
        ?>
        <div class="row">
        <?php if (isset($blocks['1'])) {?>
        <div class="span3 pi-zone-1">
            <?php foreach ($blocks['1'] as $key => $block) {
                include $blockTempalte;
            } ?>
        </div>

        <?php } ?>
        <div class="<?php echo (isset($blocks['1']) && isset($blocks['7'])) ? 'span6' : 'span9'; ?>">
            <?php if(isset($blocks['2'])) {
            ?>
            <div class="pi-zone-2">
                <?php foreach ($blocks['2'] as $key => $block) {
                    include $blockTempalte;
                } ?>
            </div>
            <?php } ?>
            <?php if(isset($blocks['3'])) {
            ?>
            <div class="pi-zone-3">
                <?php foreach ($blocks['3'] as $key => $block) {
                    include $blockTempalte;
                } ?>
            </div>
            <?php } ?>
            <?php if (isset($blocks['4'])) {
            ?>
            <div class="pi-zone-4">
            <?php foreach ($blocks['4'] as $key => $block) {
                include $blockTempalte;
            } ?>
            </div>
            <?php } ?>

            <!-- Module content -->
            <?php if (!empty($content)) { ?>
                <div class="pi-zone-module row-fluid"><?php echo $content; ?></div>
            <?php } ?>

            <?php if (isset($blocks['5'])) {
            ?>
            <div class="pi-zone-5">
                <?php foreach ($blocks['5'] as $key => $block) {
                    include $blockTempalte;
                } ?>
            </div>
            <?php } ?>
            <?php if (isset($blocks['6'])) {
            ?>
            <div class="pi-zone-6">
                <?php foreach ($blocks['6'] as $key => $block) {
                    include $blockTempalte;
                } ?>
            </div>
            <?php } ?>
        </div>
        <?php if (isset($blocks['7'])) { ?>
        <div class="span3 pi-zone-7">
            <?php foreach ($blocks['7'] as $key => $block) {
                include $blockTempalte;
            } ?>
        </div>
        <?php } ?>
        </div>
        <?php if (isset($blocks['8'])) {?>
        <div class="pi-zone-8">
            <?php foreach ($blocks['8'] as $key => $block) {
                include $blockTempalte;
            } ?>
        </div>
        <?php } ?>
    </div>

    <!-- Footer: sitelink -->
    <div class="footer">
        <div class="container">
            <div class="footer-line"></div>
            <a href="<?php echo Pi::url('page/terms'); ?>" title="<?php _e('Terms of use'); ?>"><?php _e('Terms of use'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/privacy'); ?>" title="<?php _e('Privacy guidelines'); ?>"><?php _e('Privacy guidelines'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/license'); ?>" title="<?php _e('License'); ?>"><?php _e('License'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/about'); ?>" title="<?php _e('About us'); ?>"><?php _e('About us'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/contact'); ?>" title="<?php _e('Contact us'); ?>"><?php _e('Contact us'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/join'); ?>" title="<?php _e('Join us'); ?>"><?php _e('Join us'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/help'); ?>" title="<?php _e('Help'); ?>"><?php _e('Help'); ?></a><span class="divider">|</span>
            <a href="<?php echo Pi::url('page/sitemap'); ?>" title="<?php _e('Sitemap'); ?>"><?php _e('Sitemap'); ?></a> <br/>
            <a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>">&copy;<?php echo $this->escape($sitename); ?></a><span class="divider">|</span>
            <a href="http://www.xoopsengine.org" title="Pi Engine" target="_blank">Powered by Pi Engine</a><span class="divider">|</span> 
            <a href="http://www.xoopsengine.org" title="Pi Engine" target="_blank">Design of Pi Engine</a><span class="divider">|</span>
        </div>
        <!-- Show execution time -->
        <?php $time = microtime(true) - Pi::startTime(); ?>
        <span style="font-size: 80%;" title="<?php _e('Execution time'); ?>"><?php echo $time; ?></span>
    </div>
    <?php echo $this->assemble('footScript', 4); ?>
</body>
</html>